name: Java CI with Maven - Test, package, and SonarCloud Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configurer Java 21 avec Corretto
      - name: Set up Java 21 with Corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # Étape 3 : Définir SONAR_TOKEN comme variable d'environnement
      - name: Set SONAR_TOKEN
        run: echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV

      # Étape 4 : Analyser le projet avec SonarCloud
      - name: Run SonarCloud analysis
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-') -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Étape 5 : Construire le projet avec Maven (après analyse SonarCloud)
      - name: Build with Maven
        run: mvn -B package
