name: Documentation

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  generate-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Build and generate Javadoc
      run: mvn -B javadoc:javadoc

    - name: Deploy documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/apidocs
        destination_dir: docs